<p><i><b>Basella alba</b></i> is an edible <a href="/wiki/Perennial_plant" title="Perennial plant">perennial</a> <a href="/wiki/Vine" title="Vine">vine</a> in the <a href="/wiki/Family_(biology)" title="Family (biology)">family</a> <a href="/wiki/Basellaceae" title="Basellaceae">Basellaceae</a>. It is found in tropical Asia and Africa where it is widely used as a <a href="/wiki/Leaf_vegetable" title="Leaf vegetable">leaf vegetable</a>. It is native to the <a href="/wiki/Indian_Subcontinent" class="mw-redirect" title="Indian Subcontinent">Indian Subcontinent</a>, <a href="/wiki/Southeast_Asia" title="Southeast Asia">Southeast Asia</a> and <a href="/wiki/New_Guinea" title="New Guinea">New Guinea</a>. It is reportedly naturalized in <a href="/wiki/China" title="China">China</a>, tropical <a href="/wiki/Africa" title="Africa">Africa</a>, <a href="/wiki/Brazil" title="Brazil">Brazil</a>, <a href="/wiki/Belize" title="Belize">Belize</a>, <a href="/wiki/Colombia" title="Colombia">Colombia</a>, the <a href="/wiki/West_Indies" title="West Indies">West Indies</a>, <a href="/wiki/Fiji" title="Fiji">Fiji</a> and <a href="/wiki/French_Polynesia" title="French Polynesia">French Polynesia</a>.<sup id="cite_ref-r_1-1" class="reference"><a href="#cite_note-r-1">[1]</a></sup></p>
                    <p><i>Basella alba</i> is known under various <a href="/wiki/Common_name" title="Common name">common names</a>, including <b>Malabar Spinach</b> <b>vine spinach</b>, <b>red vine spinach</b>, <b>climbing spinach</b>, <b>creeping spinach</b>, <b>buffalo spinach</b> and <b>Ceylon spinach</b> among <a href="#Names">others</a>.<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup><sup id="cite_ref-ibiscan.tripod.com_3-0" class="reference"><a href="#cite_note-ibiscan.tripod.com-3">[3]</a></sup><sup id="cite_ref-4" class="reference"><a href="#cite_note-4">[4]</a></sup></p>
                    <p></p>
                    <h2><span class="mw-headline" id="Description">Description</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=1" title="Edit section: Description">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <p><i>Basella alba</i> is a fast-growing, soft-stemmed <a href="/wiki/Vine" title="Vine">vine</a>, reaching 10 metres (33&#160;ft) in length. Its thick, semi-<a href="/wiki/Succulent" class="mw-redirect" title="Succulent">succulent</a>, heart-shaped leaves have a mild flavour and <a href="/wiki/Mucilaginous" class="mw-redirect" title="Mucilaginous">mucilaginous</a> texture. It is rich in vitamins A and C, iron and calcium. It has been shown to contain certain phenolic phytochemicals and it has antioxidant properties.<sup class="noprint Inline-Template Template-Fact" style="white-space:nowrap;">[<i><a href="/wiki/Wikipedia:Citation_needed" title="Wikipedia:Citation needed"><span title="This claim needs references to reliable sources. (July 2015)">citation needed</span></a></i>]</sup></p>
                    <p>It is also called Malabar Spinach. There are two varieties - green and red. The stem of the <i>Basella alba</i> is green and the stem of the cultivar <i>Basella alba</i> 'Rubra' is reddish-purple; the leaves in both cases are green. The stem when crushed usually emits a strong scent. Malabar Spinach can be found at many <a href="/wiki/Asian_supermarkets" class="mw-redirect" title="Asian supermarkets">Asian supermarkets</a>, as well as farmers' markets.</p>
                    <h3><span class="mw-headline" id="Soil_and_climate_requirements">Soil and climate requirements</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=2" title="Edit section: Soil and climate requirements">edit</a><span class="mw-editsection-bracket">]</span></span></h3>
                    <p><i>Basella alba</i> grows well under full sunlight in hot, humid climates and in areas lower than 500 metres (1,600&#160;ft) above sea level. The plant is native to <a href="/wiki/Malabar_(Northern_Kerala)" class="mw-redirect" title="Malabar (Northern Kerala)">tropical Asia</a>.<sup id="cite_ref-WorldCrops_Malabar_Spinach_5-0" class="reference"><a href="#cite_note-WorldCrops_Malabar_Spinach-5">[5]</a></sup> Growth is slow in low temperatures resulting in low yields. Flowering is induced during the short-day months of November to February. It grows best in sandy loam soils rich in organic matter with <a href="/wiki/PH" title="PH">pH</a> ranging from 5.5 to 8.0.</p>
                    <h2><span class="mw-headline" id="Food_uses">Food uses</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=3" title="Edit section: Food uses">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <p>Typical of leaf vegetables, Malabar spinach is high in <a href="/wiki/Vitamin_A" title="Vitamin A">vitamin A</a>, <a href="/wiki/Vitamin_C" title="Vitamin C">vitamin C</a>, <a href="/wiki/Iron" title="Iron">iron</a>, and <a href="/wiki/Calcium" title="Calcium">calcium</a>. It is low in calories by volume, but high in protein per calorie. The succulent <a href="/wiki/Mucilage" title="Mucilage">mucilage</a> is a particularly rich source of <a href="/wiki/Soluble_fiber" class="mw-redirect" title="Soluble fiber">soluble fiber</a>. Among many other possibilities, Malabar spinach may be used to thicken <a href="/wiki/Soup" title="Soup">soups</a> or <a href="/wiki/Stir_frying" title="Stir frying">stir-fries</a> with <a href="/wiki/Garlic" title="Garlic">garlic</a> and <a href="/wiki/Chili_pepper" title="Chili pepper">chili peppers</a>.</p>
                    <p>In the Philippines, the leaves of this vegetable is one of the main ingredients in an all vegetable dish called <a href="/wiki/Utan" title="Utan">utan</a> that is served over rice. It is usually cooked with sardines, onions, garlic, and parsley.</p>
                    <p>In <a href="/wiki/Karnataka_Cuisine" class="mw-redirect" title="Karnataka Cuisine">Karnataka Cuisine</a> (Karavali and Malnad regions), the leaves and stems are used to make Basale Soppu Saaru/Curry (Especially in combination with <a href="/wiki/Jackfruit" title="Jackfruit">Jackfruit</a> seed) and soupy raita with curd. <a href="/wiki/Beary" title="Beary">Beary</a> Muslims of coastal <a href="/wiki/Karnataka" title="Karnataka">Karnataka</a> prepare Basalede kunhi Pindi (small rice dumplings smeared in gravy prepared from Malabar spinach and dried <a href="/wiki/Tuna" title="Tuna">tuna</a> ). In <a href="/wiki/Bengali_cuisine" title="Bengali cuisine">Bengali cuisine</a> it is widely used both in a vegetable dish, cooked with red pumpkin, and in non-vegetarian dishes, cooked with the bones of the <a href="/wiki/Ilish" title="Ilish">Ilish</a> fish and may also be cooked with shrimps. In <a href="/wiki/Andhra_Pradesh" title="Andhra Pradesh">Andhra Pradesh</a>, a southern state in India, a curry of Basella and Yam is made popularly known as Kanda Bachali Koora [Yam and Basella curry]. Also it used to make the snack item bachali koora bajji. In <a href="/wiki/Odisha" title="Odisha">Odisha</a>, <a href="/wiki/India" title="India">India</a>, it is used to make Curries and Saaga (any type of dish made from green leafy vegetables is called Saaga in Odisha). In the <a href="/wiki/Western_Ghats" title="Western Ghats">Western Ghats</a> in <a href="/wiki/Maharashtra" title="Maharashtra">Maharashtra</a>, <a href="/wiki/India" title="India">India</a>, it is used to make <a href="/wiki/Pakora" title="Pakora">bhaji</a> <big>(भजी)</big>. It is also known as daento or valchi bhaji in Konkani. A popular <a href="/wiki/Mangalorean" class="mw-redirect" title="Mangalorean">Mangalorean</a> dish is "Valchi Bhaji and Shrimp - Curry".</p>
                    <p>The vegetable is used in <a href="/wiki/Chinese_cuisine" title="Chinese cuisine">Chinese cuisine</a>. It has many names including flowing water vegetable. It is often used in stir-frys and soups. In <a href="/wiki/Vietnam" title="Vietnam">Vietnam</a>, particularly the north, it is cooked with crab meat, <a href="/wiki/Luffa" title="Luffa">luffa</a> and <a href="/wiki/Jute#Food" title="Jute">jute</a> to make soup.</p>
                    <p>In Africa, the mucilaginous cooked shoots are most commonly used.<sup id="cite_ref-prota_6-0" class="reference"><a href="#cite_note-prota-6">[6]</a></sup></p>
                    <h2><span class="mw-headline" id="Names">Names</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=4" title="Edit section: Names">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <p><i>Basella alba</i> is usually referred to as the "<a href="/wiki/Spinach" title="Spinach">spinach</a>" equivalent of a certain country in <a href="/wiki/English_language" title="English language">English</a>, even though it is not related to the true spinach (<i><a href="/wiki/Spinacia_oleracea" class="mw-redirect" title="Spinacia oleracea">Spinacia oleracea</a></i>). Examples include "Malabar spinach", "Ceylon spinach", "Indian spinach", "Surinam spinach", "Chinese spinach", or "Vietnamese spinach". Other common names include "vine spinach", "red vine spinach", "climbing spinach", "creeping spinach", "buffalo spinach", "Malabar nightshade", and "broad bologi".</p>
                    <p>In <a href="/wiki/South_Asia" title="South Asia">South Asia</a>, it is known as <i>pui shak</i> <big>(পুঁই শাক)</big> in <a href="/wiki/Bengali_language" title="Bengali language">Bengali</a>; <i>poi ni bhaji</i> in <a href="/wiki/Gujarati_language" title="Gujarati language">Gujarati</a>; <i>basale soppu(ಬಸಳೆ ಸೊಪ್ಪು)</i> in <a href="/wiki/Kannada_language" class="mw-redirect" title="Kannada language">Kannada</a>; <i>valchi bhaji</i> or <i>daento</i> or <i>vauchi bhaji</i> in <a href="/wiki/Konkani_language" title="Konkani language">Konkani</a>; <i>vallicheera</i> <big>(വള്ളിച്ചീര )</big> in <a href="/wiki/Malayalam_language" class="mw-redirect" title="Malayalam language">Malayalam</a>; <i>mayalu</i> <big>(मायाळू)</big> in <a href="/wiki/Marathi_language" title="Marathi language">Marathi</a>; <i>poi saaga</i> <big>(ପୋଈ ଶାଗ)</big> in <a href="/wiki/Odia_language" title="Odia language">Odia</a>; <i>vel niviti</i> (<i>sudu</i>) in <a href="/wiki/Sinhala_language" class="mw-redirect" title="Sinhala language">Sinhalese</a>; kodip pasaLi <big>(கொடிப்பசலை)</big> in <a href="/wiki/Tamil_language" title="Tamil language">Tamil</a>; <i>bachhali</i> <big>(బచ్చలి)</big> in <a href="/wiki/Telugu_language" title="Telugu language">Telugu</a>; and <i>basale</i> in <a href="/wiki/Tulu_language" title="Tulu language">Tulu</a>.</p>
                    <p>In <a href="/wiki/Southeast_Asia" title="Southeast Asia">Southeast Asia</a>, it is known as <i>kubay</i> in <a href="/wiki/Ibanag_language" title="Ibanag language">Ibanag</a>; <i>libatu</i> in <a href="/wiki/Kapampangan_language" title="Kapampangan language">Kapampangan</a>; and <i>alugbati</i> in <a href="/wiki/Tagalog_language" title="Tagalog language">Tagalog</a> and the <a href="/wiki/Visayan_languages" title="Visayan languages">Visayan languages</a> of the <a href="/wiki/Philippines" title="Philippines">Philippines</a>. It is known as <i>pak plang</i> <big>(ผักปลัง)</big> in <a href="/wiki/Thai_language" title="Thai language">Thai</a>; and <i>mồng tơi</i> in <a href="/wiki/Vietnamese_language" title="Vietnamese language">Vietnamese</a>.<sup id="cite_ref-WorldCrops_Malabar_Spinach_5-1" class="reference"><a href="#cite_note-WorldCrops_Malabar_Spinach-5">[5]</a></sup></p>
                    <p>In <a href="/wiki/East_Asia" title="East Asia">East Asia</a>, it is known as 潺菜, 木耳菜, 落葵 or 蚕菜, being <i>saan choy</i>, <i>xan choy</i>, <i>shan tsoi</i>, <i>luo kai</i>, <i>shu chieh</i>, and <i>lo kwai</i> in some of readings of <a href="/wiki/Cantonese_language" class="mw-redirect" title="Cantonese language">Cantonese</a>; and <i>tsurumurasaki</i> (つるむらさき) in <a href="/wiki/Japanese_language" title="Japanese language">Japanese</a>.<sup id="cite_ref-WorldCrops_Malabar_Spinach_5-2" class="reference"><a href="#cite_note-WorldCrops_Malabar_Spinach-5">[5]</a></sup></p>
                    <p>In <a href="/wiki/Latin_America" title="Latin America">Latin America</a>, it is known as <span lang="es"><i>espinaca china</i></span> (<span title="Representation in the International Phonetic Alphabet (IPA)" class="IPA"><a href="/wiki/Help:IPA/Spanish" title="Help:IPA/Spanish">[espiˈnaka ˈtʃina]</a></span>, "Chinese spinach") or <span lang="es"><i>espinaca de Malabar</i></span> (<span title="Representation in the International Phonetic Alphabet (IPA)" class="IPA"><a href="/wiki/Help:IPA/Spanish" title="Help:IPA/Spanish">[espiˈnaka ðe malaˈβar]</a></span>, "Malabar spinach") in <a href="/wiki/Spanish_language" title="Spanish language">Spanish</a>, and <span lang="pt"><i>bertalha</i></span> (<span title="Representation in the International Phonetic Alphabet (IPA)" class="IPA"><a href="/wiki/Help:IPA/Portuguese" title="Help:IPA/Portuguese">[beʁˈtaʎɐ]</a></span>, etymology is tentatively "creepy green", "dense green") or <span lang="pt"><i>espinafre indiano</i></span> (<span title="Representation in the International Phonetic Alphabet (IPA)" class="IPA"><a href="/wiki/Help:IPA/Portuguese" title="Help:IPA/Portuguese">[ispiˈnafɾ ĩdʒiˈɐ̃nu]</a></span>, "Indian spinach") in <a href="/wiki/Portuguese_language" title="Portuguese language">Portuguese</a>.</p>
                    <h2><span class="mw-headline" id="References">References</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=5" title="Edit section: References">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <div class="reflist" style="list-style-type: decimal;">
                        <div class="mw-references-wrap">
                            <ol class="references">
                                <li id="cite_note-r-1"><span class="mw-cite-backlink">^ <a href="#cite_ref-r_1-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-r_1-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><a rel="nofollow" class="external text" href="http://apps.kew.org/wcsp/namedetail.do?name_id=360840">Kew World Checklist of Selected Plant Families, <i>Basella alba</i></a></span></li>
                                <li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><cite class="citation web"><a rel="nofollow" class="external text" href="http://parkseed.com/product.aspx?p=05660-PK-P1">"Red Stem Malabar Spinach Seeds"</a>. <i>Park Seed</i>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.atitle=Red+Stem+Malabar+Spinach+Seeds&amp;rft.genre=unknown&amp;rft.jtitle=Park+Seed&amp;rft_id=http%3A%2F%2Fparkseed.com%2Fproduct.aspx%3Fp%3D05660-PK-P1&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&#160;</span></span>
                                    </span>
                                </li>
                                <li id="cite_note-ibiscan.tripod.com-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-ibiscan.tripod.com_3-0">^</a></b></span> <span class="reference-text"><cite class="citation web"><a rel="nofollow" class="external text" href="http://ibiscan.tripod.com/id9.html">"Dictionary of Philippine Vegetables"</a><span class="reference-accessdate">. Retrieved <span class="nowrap">August 31,</span> 2012</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.btitle=Dictionary+of+Philippine+Vegetables&amp;rft.genre=unknown&amp;rft_id=http%3A%2F%2Fibiscan.tripod.com%2Fid9.html&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&#160;</span></span>
                                    </span>
                                </li>
                                <li id="cite_note-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-4">^</a></b></span> <span class="reference-text"><cite class="citation web"><a rel="nofollow" class="external text" href="http://www.foodrecap.net/health/alugbati-benefits/">"Uses and Health Benefits of Alugbati / Malabar Spinach"</a>. <i>foodrecap.net</i>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.atitle=Uses+and+Health+Benefits+of+Alugbati+%2F+Malabar+Spinach&amp;rft.genre=unknown&amp;rft.jtitle=foodrecap.net&amp;rft_id=http%3A%2F%2Fwww.foodrecap.net%2Fhealth%2Falugbati-benefits%2F&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&#160;</span></span>
                                    </span>
                                </li>
                                <li id="cite_note-WorldCrops_Malabar_Spinach-5"><span class="mw-cite-backlink">^ <a href="#cite_ref-WorldCrops_Malabar_Spinach_5-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-WorldCrops_Malabar_Spinach_5-1"><sup><i><b>b</b></i></sup></a> <a href="#cite_ref-WorldCrops_Malabar_Spinach_5-2"><sup><i><b>c</b></i></sup></a></span> <span class="reference-text"><cite class="citation web"><a rel="nofollow" class="external text" href="http://www.worldcrops.org/crops/Malabar-Spinach.cfm">"WorldCrops Malabar Spinach"</a><span class="reference-accessdate">. Retrieved <span class="nowrap">August 31,</span> 2012</span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.btitle=WorldCrops+Malabar+Spinach&amp;rft.genre=unknown&amp;rft_id=http%3A%2F%2Fwww.worldcrops.org%2Fcrops%2FMalabar-Spinach.cfm&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&#160;</span></span>
                                    </span>
                                </li>
                                <li id="cite_note-prota-6"><span class="mw-cite-backlink"><b><a href="#cite_ref-prota_6-0">^</a></b></span> <span class="reference-text">Grubben, G.J.H. &amp; Denton, O.A. (2004) Plant Resources of Tropical Africa 2. Vegetables. PROTA Foundation, Wageningen; Backhuys, Leiden; CTA, Wageningen.</span></li>
                            </ol>
                        </div>
                    </div>
                    <h2><span class="mw-headline" id="External_links">External links</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Basella_alba&amp;action=edit&amp;section=6" title="Edit section: External links">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <ul>
                        <li><cite class="citation web"><a rel="nofollow" class="external text" href="http://www.plantnames.unimelb.edu.au/Sorting/Basella.html">"&#160;Multilingual taxonomic information"</a>. <a href="/wiki/University_of_Melbourne" title="University of Melbourne">University of Melbourne</a>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.btitle=+Multilingual+taxonomic+information&amp;rft.genre=unknown&amp;rft.pub=University+of+Melbourne&amp;rft_id=http%3A%2F%2Fwww.plantnames.unimelb.edu.au%2FSorting%2FBasella.html&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&#160;</span></span>
                        </li>
                        <li>
                            <a href="/wiki/File:Commons-logo.svg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/12px-Commons-logo.svg.png" width="12" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/18px-Commons-logo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/24px-Commons-logo.svg.png 2x" data-file-width="1024" data-file-height="1376" /></a> Media related to <a href="https://commons.wikimedia.org/wiki/Basella_alba" class="extiw" title="commons:Basella alba">Basella alba</a> at Wikimedia Commons</li>
                        <li><a rel="nofollow" class="external text" href="http://database.prota.org/dbtw-wpd/exec/dbtwpub.dll?AC=QBE_QUERY&amp;BU=http%3A%2F%2Fdatabase.prota.org%2Fsearch.htm&amp;TN=PROTAB~1&amp;QB0=AND&amp;QF0=Species+Code&amp;QI0=Basella+alba&amp;RF=Webdisplay">PROTAbase on <i>Basella alba</i></a></li>
                        <li><a rel="nofollow" class="external text" href="https://web.archive.org/web/20050409205631/http://www.nre.vic.gov.au/trade/asiaveg/thes-09.htm">Photo and multilingual synonyms</a></li>
                        <li><a rel="nofollow" class="external text" href="http://edis.ifas.ufl.edu/MV138">University of Florida Agricultural Extension</a></li>
                        <li><a rel="nofollow" class="external text" href="http://www.hort.purdue.edu/newcrop/proceedings1999/v4-388.html#basellaceae">Evaluation of tropical leaf vegetables in the Virgin Islands</a></li>
                        <li><a rel="nofollow" class="external text" href="http://www.worldcrops.org/crops/Malabar-Spinach.cfm">Malabar Spinach <i>Basella alba</i>, <i>B. ruba</i></a> (WorldCrops)</li>
                        <li class="mw-empty-elt"></li>
                        <li><cite class="citation book">Dressler, S.; Schmidt, M. &amp; Zizka, G. (2014). <a rel="nofollow" class="external text" href="http://www.africanplants.senckenberg.de/root/index.php?submitForm=true&amp;page_id=77&amp;searchTextMenue=Basella+alba&amp;filterRegionIDs%5B%5D=6&amp;filterRegionIDs%5B%5D=1&amp;filterRegionIDs%5B%5D=2&amp;filterRegionIDs%5B%5D=3&amp;filterRegionIDs%5B%5D=5">"<i>Basella alba</i>"</a>. <a rel="nofollow" class="external text" href="http://www.africanplants.senckenberg.de"><i>African plants – a Photo Guide</i></a>. Frankfurt/Main: Forschungsinstitut Senckenberg.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ABasella+alba&amp;rft.atitle=Basella+alba&amp;rft.au=Schmidt%2C+M.&amp;rft.au=Zizka%2C+G.&amp;rft.aufirst=S.&amp;rft.aulast=Dressler&amp;rft.btitle=African+plants+%E2%80%93+a+Photo+Guide&amp;rft.date=2014&amp;rft.genre=bookitem&amp;rft.place=Frankfurt%2FMain&amp;rft.pub=Forschungsinstitut+Senckenberg&amp;rft_id=http%3A%2F%2Fwww.africanplants.senckenberg.de%2Froot%2Findex.php%3FsubmitForm%3Dtrue%26page_id%3D77%26searchTextMenue%3DBasella%2Balba%26filterRegionIDs%26%2391%3B%26%2393%3B%3D6%26filterRegionIDs%26%2391%3B%26%2393%3B%3D1%26filterRegionIDs%26%2391%3B%26%2393%3B%3D2%26filterRegionIDs%26%2391%3B%26%2393%3B%3D3%26filterRegionIDs%26%2391%3B%26%2393%3B%3D5&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook" class="Z3988"><span style="display:none;">&#160;</span></span>
                        </li>
                    </ul>
