<p><i><b>Spondias</b></i> is a genus of <a href="/wiki/Flowering_plant" title="Flowering plant">flowering plants</a> in the <a href="/wiki/Cashew" title="Cashew">cashew</a> family, <a href="/wiki/Anacardiaceae" title="Anacardiaceae">Anacardiaceae</a>. The genus consists of 17 described species, 7 of which are native to the <a href="/wiki/Neotropic_ecozone" class="mw-redirect" title="Neotropic ecozone">Neotropics</a> and about 10 are native to <a href="/wiki/Tropical_Asia" title="Tropical Asia">tropical Asia</a>. They are commonly named <b>hog plums</b>, <b>Spanish plums</b>, <b>libas</b> in <a href="/wiki/Bicol_Region" title="Bicol Region">Bikol</a> and in some cases <b>golden apples</b> for their brightly colored fruit which resemble an <a href="/wiki/Apple" title="Apple">apple</a> or small <a href="/wiki/Plum" title="Plum">plum</a> at a casual glance. They are only distantly related to apple and plum trees, however. A more unequivocal common name is <b>mombins</b>.</p>
                    <div class="thumb tleft">
                        <div class="thumbinner" style="width:202px;">
                            <a href="/wiki/File:2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG/200px-2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG" width="200" height="169" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG/300px-2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/dc/2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG/400px-2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG 2x" data-file-width="3750" data-file-height="3168" /></a>
                            <div class="thumbcaption">
                                <div class="magnify">
                                    <a href="/wiki/File:2014-10-11_Spondias_dulcis_Goldpflaume_anagoria.JPG" class="internal" title="Enlarge"></a>
                                </div>
                                <i>Spondias dulcis</i>, fruit, section and seed</div>
                        </div>
                    </div>

<p>A theory regarding the name of the city of <a href="/wiki/Bangkok" title="Bangkok">Bangkok</a>, Thailand is that the name is derived from <a href="/wiki/Thai_language" title="Thai language">Thai</a>: <span lang="th" xml:lang="th">-มะกอกน้ำ</span>; <a href="/wiki/Royal_Thai_General_System_of_Transcription" title="Royal Thai General System of Transcription"><span class="smallcaps" style="font-variant:small-caps;">rtgs</span></a>:&#160;<span title="Thai transliteration" class="Unicode" style="white-space:normal; text-decoration: none"><i>makok nam</i></span> 'water olive', the <a href="/wiki/Thai_language" title="Thai language">Thai</a> name for the fruit of <i><a href="/wiki/Spondias_dulcis" title="Spondias dulcis">Spondias dulcis</a></i>.<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> In Cambodia, <i>Spondias pinnata</i> is called /pɷːn siː pʰlaɛ/ (ពោនស៊ីផ្លែ) or /məkaʔ prẹj/ (ម្កាក់ព្រៃ),<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup> and <i>Spondias dulcis</i> simply /məkaʔ/ (ម្កាក់). <i>Spondias pinnata</i> is called <i>Pulicha kaai</i> in the Tamil language, which means "sour fruit." It is also called "Amate Kaai" in the <a href="/wiki/Kannada_language" class="mw-redirect" title="Kannada language">Kannada language</a>, <i>Ambade</i> in <a href="/wiki/Tulu_language" title="Tulu language">Tulu</a> and <a href="/wiki/Konkani" class="mw-redirect" title="Konkani">Konkani</a>. In Sri Lanka it is called <i>Amberella</i>.</p>
                    <div style="clear:left;"></div>
                    <p></p>
                    <p></p>
                    <h2><span class="mw-headline" id="Description">Description</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Spondias&amp;action=edit&amp;section=1" title="Edit section: Description">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <p>They are <a href="/wiki/Deciduous" title="Deciduous">deciduous</a> or <a href="/wiki/Evergreen" title="Evergreen">semi-evergreen</a> <a href="/wiki/Tree" title="Tree">trees</a> growing to 25 m tall. The <a href="/wiki/Leaf" title="Leaf">leaves</a> are spirally arranged, <a href="/wiki/Pinnate" class="mw-redirect" title="Pinnate">pinnate</a>, rarely bipinnate or simple. The <a href="/wiki/Fruit" title="Fruit">fruit</a> is a <a href="/wiki/Drupe" title="Drupe">drupe</a> similar to a small <a href="/wiki/Mango" title="Mango">mango</a> (in the related genus <i><a href="/wiki/Mangifera" title="Mangifera">Mangifera</a></i>), 4–10&#160;cm long, ripening yellow or orange. It has a single <a href="/wiki/Seed" title="Seed">seed</a>.</p>
                    <p>The <a href="/wiki/Malesian" class="mw-redirect" title="Malesian">Malesian</a> species of <i>Spondias</i> were revised by <a href="/w/index.php?title=Ding_Hou&amp;action=edit&amp;redlink=1" class="new" title="Ding Hou (page does not exist)">Ding Hou</a> in 1978.<sup id="cite_ref-dinghou1978_4-0" class="reference"><a href="#cite_note-dinghou1978-4">[4]</a></sup> The most recently recognized species, <i><a href="/w/index.php?title=Spondias_testudinis&amp;action=edit&amp;redlink=1" class="new" title="Spondias testudinis (page does not exist)">Spondias testudinis</a></i>, was described in 1998.<sup id="cite_ref-mitchell1998_5-0" class="reference"><a href="#cite_note-mitchell1998-5">[5]</a></sup></p>
                    <h2><span class="mw-headline" id="As_food">As food</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Spondias&amp;action=edit&amp;section=2" title="Edit section: As food">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <div class="thumb tright">
                        <div class="thumbinner" style="width:162px;">
                            <a href="/wiki/File:Ma-kok.jpg" class="image"><img alt="" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Ma-kok.jpg/160px-Ma-kok.jpg" width="160" height="147" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/29/Ma-kok.jpg/240px-Ma-kok.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/29/Ma-kok.jpg/320px-Ma-kok.jpg 2x" data-file-width="1963" data-file-height="1809" /></a>
                            <div class="thumbcaption">
                                <div class="magnify">
                                    <a href="/wiki/File:Ma-kok.jpg" class="internal" title="Enlarge"></a>
                                </div>
                                Preserved ma-kok, sweet and sour with chili</div>
                        </div>
                    </div>
                    <p>About 10 species of <i>Spondias</i> bear edible fruits and have been domesticated for fruit production. These fruits are also consumed by herbivorous mammals such as deer.</p>
                    <p>In the <a href="/wiki/Western_Ghats" title="Western Ghats">Western Ghats</a> of <a href="/wiki/Karnataka" title="Karnataka">Karnataka</a> flower buds and tender fruits are used in pickle preparation. In <a href="/wiki/Thai_cuisine" title="Thai cuisine">Thai cuisine</a> both the fruits and the tender leaves are eaten.</p>
                    <h2><span class="mw-headline" id="Selected_species">Selected species</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Spondias&amp;action=edit&amp;section=3" title="Edit section: Selected species">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <ul>
                        <li><i><a href="/wiki/Spondias_cytherea" class="mw-redirect" title="Spondias cytherea">Spondias cytherea</a></i> Sonn.</li>
                        <li><i><a href="/wiki/Spondias_dulcis" title="Spondias dulcis">Spondias dulcis</a></i> – <a href="/wiki/Tahitian_apple" class="mw-redirect" title="Tahitian apple">Tahitian apple</a>, pommecythere (Trinidad &amp; Tobago)</li>
                        <li><i><a href="/w/index.php?title=Spondias_haplophylla&amp;action=edit&amp;redlink=1" class="new" title="Spondias haplophylla (page does not exist)">Spondias haplophylla</a></i></li>
                        <li><i><a href="/w/index.php?title=Spondias_indica&amp;action=edit&amp;redlink=1" class="new" title="Spondias indica (page does not exist)">Spondias indica</a></i></li>
                        <li><i><a href="/w/index.php?title=Spondias_lakonensis&amp;action=edit&amp;redlink=1" class="new" title="Spondias lakonensis (page does not exist)">Spondias lakonensis</a></i></li>
                        <li><i><a href="/wiki/Spondias_mombin" title="Spondias mombin">Spondias mombin</a></i> – <a href="/wiki/Yellow_mombin" class="mw-redirect" title="Yellow mombin">Yellow mombin</a>, gully plum, Ashanti plum, "Java plum"</li>
                        <li><i><a href="/wiki/Spondias_pinnata" title="Spondias pinnata">Spondias pinnata</a></i></li>
                        <li><i><a href="/wiki/Spondias_purpurea" title="Spondias purpurea">Spondias purpurea</a></i> L. – <a href="/wiki/Jocote" class="mw-redirect" title="Jocote">Jocote</a>, purple mombin, red mombin, ciruela, siniguela, sirigwela</li>
                        <li><i><a href="/wiki/Spondias_radlkoferi" title="Spondias radlkoferi">Spondias radlkoferi</a></i></li>
                        <li><i><a href="/wiki/Spondias_tuberosa" title="Spondias tuberosa">Spondias tuberosa</a></i> – <a href="/wiki/Umb%C3%BA" class="mw-redirect" title="Umbú">Umbú</a>, imbu, Brazil plum</li>
                        <li><i><a href="/w/index.php?title=Spondias_venulosa&amp;action=edit&amp;redlink=1" class="new" title="Spondias venulosa (page does not exist)">Spondias venulosa</a></i></li>
                    </ul>
                    <h2><span class="mw-headline" id="References">References</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Spondias&amp;action=edit&amp;section=4" title="Edit section: References">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
                    <div class="reflist" style="list-style-type: decimal;">
                        <div class="mw-references-wrap">
                            <ol class="references">
                                <li id="cite_note-GRIN-1"><span class="mw-cite-backlink"><b><a href="#cite_ref-GRIN_1-0">^</a></b></span> <span class="reference-text"><cite class="citation web"><a rel="nofollow" class="external text" href="http://www.ars-grin.gov/cgi-bin/npgs/html/genus.pl?11429">"<i>Spondias</i> L."</a>. <i>Germplasm Resources Information Network</i>. United States Department of Agriculture. 2009-11-23<span class="reference-accessdate">. Retrieved <span class="nowrap">2010-02-12</span></span>.</cite><span title="ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3ASpondias&amp;rft.atitle=Spondias+L.&amp;rft.date=2009-11-23&amp;rft.genre=unknown&amp;rft.jtitle=Germplasm+Resources+Information+Network&amp;rft_id=http%3A%2F%2Fwww.ars-grin.gov%2Fcgi-bin%2Fnpgs%2Fhtml%2Fgenus.pl%3F11429&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal" class="Z3988"><span style="display:none;">&#160;</span></span>
                                    </span>
                                </li>
                                <li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><a rel="nofollow" class="external text" href="http://www.watarun.org/historyx.html">"ชั้นและตำบลที่ตั้งวัด"</a>, <i>watarun.org</i>, accessed March 29, 2011.</span></li>
                                <li id="cite_note-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-3">^</a></b></span> <span class="reference-text">LETI, Mathieu, HUL Sovanmoly, Jean-Gabriel FOUCHÉ, CHENG Sun Kaing, Bruno DAVID, <i>Flore photographique du Cambodge</i>, Paris: Privat, 2013, p. 63.</span></li>
                                <li id="cite_note-dinghou1978-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-dinghou1978_4-0">^</a></b></span> <span class="reference-text"><i>Flora Malesiana</i> series 1, 8(3):395-577.</span></li>
                                <li id="cite_note-mitchell1998-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-mitchell1998_5-0">^</a></b></span> <span class="reference-text">John D. Mitchell and Douglas C. Daly. 1998. "The "tortoise's cajá" - a new species of <i>Spondias</i> (Anacardiaceae) from southwestern Amazonia" <i>Brittonia</i> <b>50</b>( ):447-451.</span></li>
                            </ol>
                        </div>
                    </div>
                    <h2><span class="mw-headline" id="External_links">External links</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Spondias&amp;action=edit&amp;section=5" title="Edit section: External links">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
